<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <brand>
        <headerColor>#F40000</headerColor>
        <logo>institute_logo1</logo>
        <logoVersion>1</logoVersion>
        <shouldOverrideOrgTheme>true</shouldOverrideOrgTheme>
    </brand>
    <description>Institute Management</description>
    <formFactors>Small</formFactors>
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>true</isNavTabPersistenceDisabled>
    <isOmniPinnedViewEnabled>false</isOmniPinnedViewEnabled>
    <label>Institute</label>
    <navType>Console</navType>
    <setupExperience>all</setupExperience>
    <tabs>standard-home</tabs>
    <tabs>standard-Lead</tabs>
    <tabs>student__c</tabs>
    <tabs>Faculty__c</tabs>
    <tabs>Course__c</tabs>
    <tabs>Batch__c</tabs>
    <tabs>Rating__c</tabs>
    <tabs>Commission__c</tabs>
    <tabs>Employee__c</tabs>
    <tabs>Car__c</tabs>
    <tabs>Car_Service__c</tabs>
    <tabs>Car_Accessory__c</tabs>
    <tabs>Project__c</tabs>
    <uiType>Lightning</uiType>
    <utilityBar>Institute_UtilityBar</utilityBar>
    <workspaceConfig>
        <mappings>
            <tab>Batch__c</tab>
        </mappings>
        <mappings>
            <tab>Car_Accessory__c</tab>
        </mappings>
        <mappings>
            <tab>Car_Service__c</tab>
        </mappings>
        <mappings>
            <tab>Car__c</tab>
        </mappings>
        <mappings>
            <tab>Commission__c</tab>
        </mappings>
        <mappings>
            <tab>Course__c</tab>
        </mappings>
        <mappings>
            <tab>Employee__c</tab>
        </mappings>
        <mappings>
            <tab>Faculty__c</tab>
        </mappings>
        <mappings>
            <tab>Project__c</tab>
        </mappings>
        <mappings>
            <tab>Rating__c</tab>
        </mappings>
        <mappings>
            <tab>standard-Lead</tab>
        </mappings>
        <mappings>
            <tab>standard-home</tab>
        </mappings>
        <mappings>
            <tab>student__c</tab>
        </mappings>
    </workspaceConfig>
</CustomApplication>
