<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <isOmniPinnedViewEnabled>false</isOmniPinnedViewEnabled>
    <label>Salesforce CMS</label>
    <navType>Console</navType>
    <tabs>standard-CmsAuthorHome</tabs>
    <tabs>standard-CmsChannel</tabs>
    <tabs>standard-CmsWorkspaces</tabs>
    <tabs>standard-CmsExperiences</tabs>
    <tabs>Commission__c</tabs>
    <tabs>Employee__c</tabs>
    <tabs>Car__c</tabs>
    <tabs>Car_Service__c</tabs>
    <tabs>Car_Accessory__c</tabs>
    <tabs>Project__c</tabs>
    <uiType>Lightning</uiType>
    <workspaceConfig>
        <mappings>
            <tab>Car_Accessory__c</tab>
        </mappings>
        <mappings>
            <tab>Car_Service__c</tab>
        </mappings>
        <mappings>
            <tab>Car__c</tab>
        </mappings>
        <mappings>
            <tab>Commission__c</tab>
        </mappings>
        <mappings>
            <tab>Employee__c</tab>
        </mappings>
        <mappings>
            <tab>Project__c</tab>
        </mappings>
        <mappings>
            <tab>standard-CmsAuthorHome</tab>
        </mappings>
        <mappings>
            <tab>standard-CmsChannel</tab>
        </mappings>
        <mappings>
            <tab>standard-CmsExperiences</tab>
        </mappings>
        <mappings>
            <tab>standard-CmsWorkspaces</tab>
        </mappings>
    </workspaceConfig>
</CustomApplication>
