<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <formFactors>Small</formFactors>
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <isOmniPinnedViewEnabled>false</isOmniPinnedViewEnabled>
    <label>Service Console</label>
    <navType>Console</navType>
    <setupExperience>service</setupExperience>
    <tabs>standard-Case</tabs>
    <tabs>standard-Contact</tabs>
    <tabs>standard-Account</tabs>
    <tabs>standard-report</tabs>
    <tabs>standard-Dashboard</tabs>
    <tabs>standard-home</tabs>
    <tabs>Commission__c</tabs>
    <tabs>Employee__c</tabs>
    <tabs>Car__c</tabs>
    <tabs>Car_Service__c</tabs>
    <tabs>Car_Accessory__c</tabs>
    <tabs>standard-Incident</tabs>
    <tabs>standard-Problem</tabs>
    <tabs>standard-ChangeRequest</tabs>
    <tabs>Project__c</tabs>
    <tabs>Knowledge__kav</tabs>
    <uiType>Lightning</uiType>
    <utilityBar>LightningService_UtilityBar</utilityBar>
    <workspaceConfig>
        <mappings>
            <tab>Car_Accessory__c</tab>
        </mappings>
        <mappings>
            <tab>Car_Service__c</tab>
        </mappings>
        <mappings>
            <tab>Car__c</tab>
        </mappings>
        <mappings>
            <tab>Commission__c</tab>
        </mappings>
        <mappings>
            <tab>Employee__c</tab>
        </mappings>
        <mappings>
            <tab>Knowledge__kav</tab>
        </mappings>
        <mappings>
            <tab>Project__c</tab>
        </mappings>
        <mappings>
            <tab>standard-Account</tab>
        </mappings>
        <mappings>
            <tab>standard-Case</tab>
        </mappings>
        <mappings>
            <tab>standard-ChangeRequest</tab>
        </mappings>
        <mappings>
            <tab>standard-Contact</tab>
        </mappings>
        <mappings>
            <tab>standard-Dashboard</tab>
        </mappings>
        <mappings>
            <tab>standard-Incident</tab>
        </mappings>
        <mappings>
            <tab>standard-Problem</tab>
        </mappings>
        <mappings>
            <tab>standard-home</tab>
        </mappings>
        <mappings>
            <tab>standard-report</tab>
        </mappings>
    </workspaceConfig>
</CustomApplication>
