public class Calculator {
    public Integer Add(Integer a, Integer b){
        Integer result = a + b;
    return result;     
    }
  
    public Integer Sub(Integer a, Integer b){
        Integer result = a - b;
    return result;
    }
    
    public Integer Mul(Integer a, Integer b){
        Integer result = a * b;
    return result;
    }
    
    public Integer Div(Integer a, Integer b){
        Integer result = a / b;
    return result;
    }
    
    String s = 'Hello World';
    String s2 = s.capitalize();
    
    //System.assertEquals('Hello World',s2);
}